version: "3.8"

services:

  routeros:
    privileged: true
    build:
      context: .
      dockerfile: routeros.dockerfile
    ports:
      - "60622:22"
    tty: true
    networks:
      default:
        ipv4_address: 172.40.0.141
    hostname: routeros

networks:
  default:
    ipam:
      config:
        - subnet: 172.40.0.0/24
